"""
Data points for national parks and cities in 48 states, taken from Wikipedia 
"""

all_waypoints = [
    "Acadia, Maine",
    "Arches, Utah",
    "Badlands, South Dakota",
    "Big Bend, Texas",
    "Biscayne, Florida",
    "Black Canyon of the Gunnison, Colorado",
    "Bryce Canyon, Utah",
    "Canyonlands, Utah",
    "Capitol Reef, Utah",
]

# parks = [
#     "Acadia, Maine",
#     "Arches, Utah",
#     "Badlands, South Dakota",
#     "Big Bend, Texas",
#     "Biscayne, Florida",
#     "Black Canyon of the Gunnison, Colorado",
#     "Bryce Canyon, Utah",
#     "Canyonlands, Utah",
#     "Capitol Reef, Utah",
#     "Carlsbad Caverns, New Mexico",
#     "Congaree, South Carolina",
#     "Crater Lake, Oregon",
#     "Cuyahoga Valley, Ohio",
#     "Death Valley, California",
#     "Everglades, Florida",
#     "Great Sand Dunes, Colorado",
#     "Great Smoky Mountains, North Carolina",
#     "Gateway Arch, Missouri",
#     "Glacier, Montana",
#     "Grand Canyon, Arizona",
#     "Great Basin, Nevada",
#     "Guadalupe Mountains, Texas",
#     "Hot Springs, Arkansas",
#     "Indiana Dunes, Indiana",
#     "Joshua Tree, California",
#     "Kings Canyon, California",
#     "Lassen Volcanic, California",
#     "Mammoth Cave, Kentucky",
#     "Mesa Verde, Colorado",
#     "Mount Rainier, Washington",
#     "North Cascades, Washington",
#     "Petrified Forest, Arizona",
#     "Pinnacles, California",
#     "Redwood, California",
#     "Rocky Mountain, Colorado",
#     "Saguaro, Arizona",
#     "Sequoia, California",
#     "Shenandoah, Virginia",
#     "Theodore Roosevelt, North Dakota",
#     "Voyageurs, Minnesota",
#     "White Sands, New Mexico",
#     "Wind Cave, South Dakota",
#     "Yellowstone, Wyoming",
#     "Yosemite, California",
#     "Zion, Utah"
# ]

# cities = [ "Birmingham, AL",
# "Phoenix, AZ",
# "Little Rock, AR",
# "Los Angeles, CA",
# "Denver, CO",
# "Bridgeport, CT",
# "Wilmington, DE",
# "Jacksonville, FL",
# "Atlanta, GA",
# "Boise, ID",
# "Chicago, IL",
# "Indianapolis, ID",
# "Des Moines, IA",
# "Wichita, KS",
# "Louisville, KY",
# "New Orleans, LA",
# "Portland, ME",
# "Baltimore, MD",
# "Boston, MA",
# "Detroit, MI",
# "Minneapolis, MN",
# "Jackson, MS",
# "Kansas City, MO",
# "Billings, MT",
# "Omaha, NE",
# "Las Vegas, NV",
# "Manchester, NH",
# "Newark, NJ",
# "Albuquerque, NM",
# "New York City, NY",
# "Charlotte, NC",
# "Fargo, ND",
# "Columbus, OH",
# "Oklahoma City, OK",
# "Portland, OR",
# "Philadelphia, PA",
# "Providence, RI",
# "Charleston, SC",
# "Sioux Falls, SD",
# "Nashville, TN",
# "Houston, TX",
# "Salt Lake City, UT",
# "Burlington, VT",
# "Virginia, Beach, VA",
# "Seattle, WA",
# "Charleston, WV",
# "Milwaukee, WI",
# "Cheyenne, WY" ]

# both = parks.extend(cities)
