"""
Data points for national parks in 48 states, taken from Wikipedia 
"""

all_waypoints = [
    "Acadia, Maine",
    "Arches, Utah",
    "Badlands, South Dakota",
    "Big Bend, Texas",
    "Biscayne, Florida",
    "Black Canyon of the Gunnison, Colorado",
    "Bryce Canyon, Utah",
    "Canyonlands, Utah",
    "Capitol Reef, Utah",
    "Carlsbad Caverns, New Mexico",
    "Congaree, South Carolina",
    "Crater Lake, Oregon",
    "Cuyahoga Valley, Ohio",
    "Death Valley, California",
    "Everglades, Florida",
    "Great Sand Dunes, Colorado",
    "Great Smoky Mountains, North Carolina",
    "Gateway Arch, Missouri",
    "Glacier, Montana",
    "Grand Canyon, Arizona",
    "Great Basin, Nevada",
    "Guadalupe Mountains, Texas",
    "Hot Springs, Arkansas",
    "Indiana Dunes, Indiana",
    "Joshua Tree, California",
    "Kings Canyon, California",
    "Lassen Volcanic, California",
    "Mammoth Cave, Kentucky",
    "Mesa Verde, Colorado",
    "Mount Rainier, Washington",
    "North Cascades, Washington",
    "Petrified Forest, Arizona",
    "Pinnacles, California",
    "Redwood, California",
    "Rocky Mountain, Colorado",
    "Saguaro, Arizona",
    "Sequoia, California",
    "Shenandoah, Virginia",
    "Theodore Roosevelt, North Dakota",
    "Voyageurs, Minnesota",
    "White Sands, New Mexico",
    "Wind Cave, South Dakota",
    "Yellowstone, Wyoming",
    "Yosemite, California",
    "Zion, Utah"
]
