all_waypoints = [ "Birmingham, AL", 
"Phoenix, AZ", 
"Little Rock, AR", 
"Los Angeles, CA",
"Denver, CO", 
"Bridgeport, CT", 
"Wilmington, DE",
"Jacksonville, FL",
"Atlanta, GA", 
"Boise, ID", 
"Chicago, IL", 
"Indianapolis, ID", 
"Des Moines, IA",
"Wichita, KS", 
"Louisville, KY", 
"New Orleans, LA", 
"Portland, ME", 
"Baltimore, MD", 
"Boston, MA", 
"Detroit, MI", 
"Minneapolis, MN", 
"Jackson, MS", 
"Kansas City, MO", 
"Billings, MT", 
"Omaha, NE", 
"Las Vegas, NV", 
"Manchester, NH",
"Newark, NJ", 
"Albuquerque, NM",
"New York City, NY", 
"Charlotte, NC", 
"Fargo, ND", 
"Columbus, OH",
"Oklahoma City, OK", 
"Portland, OR", 
"Philadelphia, PA", 
"Providence, RI", 
"Charleston, SC", 
"Sioux Falls, SD",
"Nashville, TN", 
"Houston, TX", 
"Salt Lake City, UT",
"Burlington, VT", 
"Virginia, Beach, VA", 
"Seattle, WA", 
"Charleston, WV", 
"Milwaukee, WI", 
"Cheyenne, WY" ]
